import Footer from "@/components/footer/footer";
import Header from "@/components/header/header";
import { cn } from "@/lib/cn";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const pretendard = localFont({
  src: "../assets/fonts/PretendardVariable.woff2",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

function RootLayout({ children }: Readonly<RootLayoutProps>) {
  return (
    <html lang="ko">
      <body
        className={cn(
          pretendard.className,
          "antialiased bg-slate-50 w-full flex flex-col items-center",
        )}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}

export default RootLayout;
