import { GraphData, NodeType } from "../_types/graph-view";

export const mockGraphData: GraphData = {
  nodes: [
    // React 기초 (1-10)
    {
      id: 1,
      type: NodeType.QUESTION,
      label: "React란 무엇인가요?",
      questionId: 1,
    },
    { id: 2, type: NodeType.KEYWORD, label: "React", questionId: null },
    { id: 3, type: NodeType.KEYWORD, label: "Virtual DOM", questionId: null },
    {
      id: 4,
      type: NodeType.QUESTION,
      label: "Virtual DOM의 동작 원리는?",
      questionId: 4,
    },
    { id: 5, type: NodeType.KEYWORD, label: "컴포넌트", questionId: null },
    {
      id: 6,
      type: NodeType.QUESTION,
      label: "useState와 useEffect 차이점은?",
      questionId: 6,
    },
    { id: 7, type: NodeType.KEYWORD, label: "Hook", questionId: null },
    { id: 8, type: NodeType.KEYWORD, label: "State", questionId: null },
    { id: 9, type: NodeType.KEYWORD, label: "Props", questionId: null },
    {
      id: 10,
      type: NodeType.QUESTION,
      label: "State와 Props의 차이는?",
      questionId: 10,
    },

    // React 심화 (11-20)
    { id: 11, type: NodeType.KEYWORD, label: "Lifecycle", questionId: null },
    {
      id: 12,
      type: NodeType.QUESTION,
      label: "React 컴포넌트 생명주기는?",
      questionId: 12,
    },
    { id: 13, type: NodeType.KEYWORD, label: "useMemo", questionId: null },
    { id: 14, type: NodeType.KEYWORD, label: "useCallback", questionId: null },
    {
      id: 15,
      type: NodeType.QUESTION,
      label: "React 성능 최적화 방법은?",
      questionId: 15,
    },
    { id: 16, type: NodeType.KEYWORD, label: "Context API", questionId: null },
    {
      id: 17,
      type: NodeType.QUESTION,
      label: "Context API는 언제 사용하나요?",
      questionId: 17,
    },
    { id: 18, type: NodeType.KEYWORD, label: "useReducer", questionId: null },
    { id: 19, type: NodeType.KEYWORD, label: "useRef", questionId: null },
    {
      id: 20,
      type: NodeType.QUESTION,
      label: "useRef의 용도는?",
      questionId: 20,
    },

    // JavaScript 기초 (21-35)
    { id: 21, type: NodeType.KEYWORD, label: "JavaScript", questionId: null },
    {
      id: 22,
      type: NodeType.QUESTION,
      label: "클로저란 무엇인가요?",
      questionId: 22,
    },
    { id: 23, type: NodeType.KEYWORD, label: "클로저", questionId: null },
    { id: 24, type: NodeType.KEYWORD, label: "스코프", questionId: null },
    { id: 25, type: NodeType.QUESTION, label: "호이스팅이란?", questionId: 25 },
    { id: 26, type: NodeType.KEYWORD, label: "호이스팅", questionId: null },
    { id: 27, type: NodeType.KEYWORD, label: "this", questionId: null },
    {
      id: 28,
      type: NodeType.QUESTION,
      label: "this 바인딩 규칙은?",
      questionId: 28,
    },
    { id: 29, type: NodeType.KEYWORD, label: "Promise", questionId: null },
    {
      id: 30,
      type: NodeType.QUESTION,
      label: "Promise와 async/await 차이는?",
      questionId: 30,
    },
    { id: 31, type: NodeType.KEYWORD, label: "async/await", questionId: null },
    { id: 32, type: NodeType.KEYWORD, label: "이벤트 루프", questionId: null },
    {
      id: 33,
      type: NodeType.QUESTION,
      label: "이벤트 루프 동작 원리는?",
      questionId: 33,
    },
    { id: 34, type: NodeType.KEYWORD, label: "콜백", questionId: null },
    { id: 35, type: NodeType.KEYWORD, label: "프로토타입", questionId: null },

    // TypeScript (36-45)
    {
      id: 36,
      type: NodeType.QUESTION,
      label: "프로토타입 체인이란?",
      questionId: 36,
    },
    { id: 37, type: NodeType.KEYWORD, label: "TypeScript", questionId: null },
    {
      id: 38,
      type: NodeType.QUESTION,
      label: "TypeScript를 사용하는 이유는?",
      questionId: 38,
    },
    { id: 39, type: NodeType.KEYWORD, label: "타입 추론", questionId: null },
    { id: 40, type: NodeType.KEYWORD, label: "제네릭", questionId: null },
    {
      id: 41,
      type: NodeType.QUESTION,
      label: "제네릭은 언제 사용하나요?",
      questionId: 41,
    },
    { id: 42, type: NodeType.KEYWORD, label: "인터페이스", questionId: null },
    { id: 43, type: NodeType.KEYWORD, label: "타입 별칭", questionId: null },
    {
      id: 44,
      type: NodeType.QUESTION,
      label: "interface vs type 차이는?",
      questionId: 44,
    },
    { id: 45, type: NodeType.KEYWORD, label: "유니온 타입", questionId: null },

    // Next.js (46-55)
    { id: 46, type: NodeType.KEYWORD, label: "Next.js", questionId: null },
    {
      id: 47,
      type: NodeType.QUESTION,
      label: "Next.js의 장점은?",
      questionId: 47,
    },
    { id: 48, type: NodeType.KEYWORD, label: "SSR", questionId: null },
    { id: 49, type: NodeType.KEYWORD, label: "SSG", questionId: null },
    {
      id: 50,
      type: NodeType.QUESTION,
      label: "SSR과 SSG 차이는?",
      questionId: 50,
    },
    { id: 51, type: NodeType.KEYWORD, label: "ISR", questionId: null },
    { id: 52, type: NodeType.KEYWORD, label: "App Router", questionId: null },
    {
      id: 53,
      type: NodeType.QUESTION,
      label: "App Router vs Pages Router?",
      questionId: 53,
    },
    {
      id: 54,
      type: NodeType.KEYWORD,
      label: "Server Components",
      questionId: null,
    },
    {
      id: 55,
      type: NodeType.QUESTION,
      label: "Server Components란?",
      questionId: 55,
    },

    // CSS/스타일링 (56-65)
    { id: 56, type: NodeType.KEYWORD, label: "CSS", questionId: null },
    { id: 57, type: NodeType.KEYWORD, label: "Flexbox", questionId: null },
    {
      id: 58,
      type: NodeType.QUESTION,
      label: "Flexbox 사용법은?",
      questionId: 58,
    },
    { id: 59, type: NodeType.KEYWORD, label: "Grid", questionId: null },
    {
      id: 60,
      type: NodeType.QUESTION,
      label: "Grid vs Flexbox 차이는?",
      questionId: 60,
    },
    { id: 61, type: NodeType.KEYWORD, label: "반응형", questionId: null },
    { id: 62, type: NodeType.KEYWORD, label: "미디어 쿼리", questionId: null },
    {
      id: 63,
      type: NodeType.QUESTION,
      label: "반응형 디자인 구현 방법은?",
      questionId: 63,
    },
    { id: 64, type: NodeType.KEYWORD, label: "Tailwind CSS", questionId: null },
    { id: 65, type: NodeType.KEYWORD, label: "CSS-in-JS", questionId: null },

    // 상태관리 (66-75)
    {
      id: 66,
      type: NodeType.QUESTION,
      label: "CSS-in-JS 장단점은?",
      questionId: 66,
    },
    { id: 67, type: NodeType.KEYWORD, label: "Redux", questionId: null },
    {
      id: 68,
      type: NodeType.QUESTION,
      label: "Redux 동작 원리는?",
      questionId: 68,
    },
    { id: 69, type: NodeType.KEYWORD, label: "Zustand", questionId: null },
    { id: 70, type: NodeType.KEYWORD, label: "Recoil", questionId: null },
    {
      id: 71,
      type: NodeType.QUESTION,
      label: "상태관리 라이브러리 비교?",
      questionId: 71,
    },
    { id: 72, type: NodeType.KEYWORD, label: "전역 상태", questionId: null },
    { id: 73, type: NodeType.KEYWORD, label: "로컬 상태", questionId: null },
    {
      id: 74,
      type: NodeType.QUESTION,
      label: "전역 vs 로컬 상태 사용 기준?",
      questionId: 74,
    },
    { id: 75, type: NodeType.KEYWORD, label: "불변성", questionId: null },

    // API/네트워크 (76-85)
    {
      id: 76,
      type: NodeType.QUESTION,
      label: "불변성이 중요한 이유는?",
      questionId: 76,
    },
    { id: 77, type: NodeType.KEYWORD, label: "REST API", questionId: null },
    { id: 78, type: NodeType.KEYWORD, label: "GraphQL", questionId: null },
    {
      id: 79,
      type: NodeType.QUESTION,
      label: "REST vs GraphQL 차이는?",
      questionId: 79,
    },
    { id: 80, type: NodeType.KEYWORD, label: "fetch", questionId: null },
    { id: 81, type: NodeType.KEYWORD, label: "axios", questionId: null },
    {
      id: 82,
      type: NodeType.QUESTION,
      label: "fetch vs axios 차이는?",
      questionId: 82,
    },
    { id: 83, type: NodeType.KEYWORD, label: "React Query", questionId: null },
    { id: 84, type: NodeType.KEYWORD, label: "SWR", questionId: null },
    {
      id: 85,
      type: NodeType.QUESTION,
      label: "React Query 사용 이유는?",
      questionId: 85,
    },

    // 테스트 (86-92)
    { id: 86, type: NodeType.KEYWORD, label: "테스트", questionId: null },
    { id: 87, type: NodeType.KEYWORD, label: "Jest", questionId: null },
    {
      id: 88,
      type: NodeType.QUESTION,
      label: "단위 테스트 작성법은?",
      questionId: 88,
    },
    {
      id: 89,
      type: NodeType.KEYWORD,
      label: "React Testing Library",
      questionId: null,
    },
    {
      id: 90,
      type: NodeType.QUESTION,
      label: "컴포넌트 테스트 방법은?",
      questionId: 90,
    },
    { id: 91, type: NodeType.KEYWORD, label: "E2E 테스트", questionId: null },
    { id: 92, type: NodeType.KEYWORD, label: "Cypress", questionId: null },

    // 빌드/배포 (93-100)
    { id: 93, type: NodeType.QUESTION, label: "E2E 테스트란?", questionId: 93 },
    { id: 94, type: NodeType.KEYWORD, label: "Webpack", questionId: null },
    { id: 95, type: NodeType.KEYWORD, label: "Vite", questionId: null },
    {
      id: 96,
      type: NodeType.QUESTION,
      label: "Webpack vs Vite 차이는?",
      questionId: 96,
    },
    { id: 97, type: NodeType.KEYWORD, label: "번들링", questionId: null },
    { id: 98, type: NodeType.KEYWORD, label: "트리 쉐이킹", questionId: null },
    {
      id: 99,
      type: NodeType.QUESTION,
      label: "트리 쉐이킹이란?",
      questionId: 99,
    },
    { id: 100, type: NodeType.KEYWORD, label: "CI/CD", questionId: null },
  ],
  edges: [
    // React 기초 연결
    { id: 1, sourceId: 1, targetId: 2 },
    { id: 2, sourceId: 1, targetId: 3 },
    { id: 3, sourceId: 4, targetId: 3 },
    { id: 4, sourceId: 1, targetId: 5 },
    { id: 5, sourceId: 6, targetId: 7 },
    { id: 6, sourceId: 6, targetId: 2 },
    { id: 7, sourceId: 10, targetId: 8 },
    { id: 8, sourceId: 10, targetId: 9 },
    { id: 9, sourceId: 6, targetId: 8 },

    // React 심화 연결
    { id: 10, sourceId: 12, targetId: 11 },
    { id: 11, sourceId: 12, targetId: 5 },
    { id: 12, sourceId: 15, targetId: 13 },
    { id: 13, sourceId: 15, targetId: 14 },
    { id: 14, sourceId: 15, targetId: 3 },
    { id: 15, sourceId: 17, targetId: 16 },
    { id: 16, sourceId: 17, targetId: 8 },
    { id: 17, sourceId: 20, targetId: 19 },
    { id: 18, sourceId: 20, targetId: 7 },
    { id: 19, sourceId: 18, targetId: 7 },
    { id: 20, sourceId: 17, targetId: 18 },

    // JavaScript 연결
    { id: 21, sourceId: 22, targetId: 23 },
    { id: 22, sourceId: 22, targetId: 24 },
    { id: 23, sourceId: 25, targetId: 26 },
    { id: 24, sourceId: 25, targetId: 24 },
    { id: 25, sourceId: 28, targetId: 27 },
    { id: 26, sourceId: 28, targetId: 21 },
    { id: 27, sourceId: 30, targetId: 29 },
    { id: 28, sourceId: 30, targetId: 31 },
    { id: 29, sourceId: 33, targetId: 32 },
    { id: 30, sourceId: 33, targetId: 29 },
    { id: 31, sourceId: 33, targetId: 34 },
    { id: 32, sourceId: 36, targetId: 35 },
    { id: 33, sourceId: 36, targetId: 21 },
    { id: 34, sourceId: 2, targetId: 21 },

    // TypeScript 연결
    { id: 35, sourceId: 38, targetId: 37 },
    { id: 36, sourceId: 38, targetId: 39 },
    { id: 37, sourceId: 41, targetId: 40 },
    { id: 38, sourceId: 41, targetId: 37 },
    { id: 39, sourceId: 44, targetId: 42 },
    { id: 40, sourceId: 44, targetId: 43 },
    { id: 41, sourceId: 44, targetId: 45 },
    { id: 42, sourceId: 37, targetId: 21 },

    // Next.js 연결
    { id: 43, sourceId: 47, targetId: 46 },
    { id: 44, sourceId: 47, targetId: 48 },
    { id: 45, sourceId: 47, targetId: 49 },
    { id: 46, sourceId: 50, targetId: 48 },
    { id: 47, sourceId: 50, targetId: 49 },
    { id: 48, sourceId: 50, targetId: 51 },
    { id: 49, sourceId: 53, targetId: 52 },
    { id: 50, sourceId: 53, targetId: 46 },
    { id: 51, sourceId: 55, targetId: 54 },
    { id: 52, sourceId: 55, targetId: 52 },
    { id: 53, sourceId: 46, targetId: 2 },

    // CSS 연결
    { id: 54, sourceId: 58, targetId: 57 },
    { id: 55, sourceId: 58, targetId: 56 },
    { id: 56, sourceId: 60, targetId: 59 },
    { id: 57, sourceId: 60, targetId: 57 },
    { id: 58, sourceId: 63, targetId: 61 },
    { id: 59, sourceId: 63, targetId: 62 },
    { id: 60, sourceId: 63, targetId: 56 },
    { id: 61, sourceId: 66, targetId: 65 },
    { id: 62, sourceId: 66, targetId: 56 },
    { id: 63, sourceId: 64, targetId: 56 },

    // 상태관리 연결
    { id: 64, sourceId: 68, targetId: 67 },
    { id: 65, sourceId: 68, targetId: 8 },
    { id: 66, sourceId: 71, targetId: 67 },
    { id: 67, sourceId: 71, targetId: 69 },
    { id: 68, sourceId: 71, targetId: 70 },
    { id: 69, sourceId: 74, targetId: 72 },
    { id: 70, sourceId: 74, targetId: 73 },
    { id: 71, sourceId: 74, targetId: 8 },
    { id: 72, sourceId: 76, targetId: 75 },
    { id: 73, sourceId: 76, targetId: 8 },
    { id: 74, sourceId: 67, targetId: 75 },
    { id: 75, sourceId: 16, targetId: 72 },

    // API 연결
    { id: 76, sourceId: 79, targetId: 77 },
    { id: 77, sourceId: 79, targetId: 78 },
    { id: 78, sourceId: 82, targetId: 80 },
    { id: 79, sourceId: 82, targetId: 81 },
    { id: 80, sourceId: 85, targetId: 83 },
    { id: 81, sourceId: 85, targetId: 8 },
    { id: 82, sourceId: 83, targetId: 84 },
    { id: 83, sourceId: 30, targetId: 80 },

    // 테스트 연결
    { id: 84, sourceId: 88, targetId: 86 },
    { id: 85, sourceId: 88, targetId: 87 },
    { id: 86, sourceId: 90, targetId: 89 },
    { id: 87, sourceId: 90, targetId: 5 },
    { id: 88, sourceId: 93, targetId: 91 },
    { id: 89, sourceId: 93, targetId: 92 },
    { id: 90, sourceId: 89, targetId: 87 },

    // 빌드/배포 연결
    { id: 91, sourceId: 96, targetId: 94 },
    { id: 92, sourceId: 96, targetId: 95 },
    { id: 93, sourceId: 96, targetId: 97 },
    { id: 94, sourceId: 99, targetId: 98 },
    { id: 95, sourceId: 99, targetId: 97 },
    { id: 96, sourceId: 94, targetId: 97 },
    { id: 97, sourceId: 95, targetId: 46 },
    { id: 98, sourceId: 100, targetId: 86 },

    // 크로스 도메인 연결 (더 풍부한 그래프를 위해)
    { id: 99, sourceId: 7, targetId: 8 },
    { id: 100, sourceId: 54, targetId: 5 },
    { id: 101, sourceId: 83, targetId: 29 },
    { id: 102, sourceId: 37, targetId: 2 },
    { id: 103, sourceId: 65, targetId: 2 },
    { id: 104, sourceId: 69, targetId: 7 },
    { id: 105, sourceId: 70, targetId: 7 },
  ],
};
